### PR TITLE
release: 2.0.0

### PR DESCRIPTION
**Pull request by curbengh**
Merge into master branch instead of '1.x'.

### CODE REVIEW

**Comment by curbengh** [comment]
Somehow 1.x doesn't branch out cleanly from master branch, there may have been some force-push in 1.x. The `exeunt` dep was removed from package and test, but the commit is not found in 1.x.

One way to do it is to merge 1.x into master, without commit history. Then merge https://github.com/hexojs/hexo-bunyan/pull/10/commits/8ca61f6534621d3688dd1375ea060808c73a4905.

Ping @hexojs/core

**Comment by curbengh** [comment]
Using this commit [graph tool](http://bit-booster.com/graph.html) and [git log](https://github.com/hexojs/hexo-bunyan/files/3565715/git-log.txt), we can see master and 1.x diverged from 1.8.10. Master branch skipped 2fed5a6...8b43e99, while 1.x skipped f812975...d1b1764.

git-log

---

I propose the following steps:
1. Create a new branch `master.bk` from `master`.
2. Remove `master` branch.
3. Create a new branch `master` from `1.x`.
4. Force-push `master` branch. (requires maintainer permission)
5. Retain `1.x` branch.

**Comment by yoshinorin** [comment]
@curbengh 
No objection 👍

**Comment by SukkaW** [comment]
@curbengh Currently master branch is not the default branch. You should able to force-push to master branch without difficulties.

**Comment by curbengh** [comment]
Done.

master


https://github.com/hexojs/hexo-bunyan/pull/12

**Pull request closed without merging**
