### PR TITLE
release: 2.0.0

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Comment by curbengh** [comment]
Shall we merge to master branch and set master branch as default?

**Review by SukkaW — APPROVED** [review]

**Comment by SukkaW** [comment]
Anyway, since we have a hexo-forked version of bunyan, should we rewrite this in ES6-standard?

**Comment by yoshinorin** [comment]
@curbengh @SukkaW 
Maintainance of the upstream repository has been abandoned. IMHO we might as well set master branch as default and rewrite ES6-standard.

**Comment by curbengh** [comment]
Another PR https://github.com/hexojs/hexo-bunyan/pull/11 merge into master branch instead.

Somehow https://github.com/hexojs/hexo-bunyan/pull/11 messed  up this PR.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo-bunyan/pull/12

**Pull request closed without merging**
