### PR TITLE
release: 2.0.0

### PR DESCRIPTION
**Pull request by curbengh**

### CODE REVIEW

**Review by SukkaW — APPROVED** [review]

**Review by yoshinorin — APPROVED** [review]
I checked the current branches. It seems good.

**Comment by curbengh** [comment]
Please set "master" as default branch. I've removed "2.x" branch.

**Comment by curbengh** [comment]
I don't have permission to publish because @hexojs/core is not an owner. @NoahDragon

**Comment by SukkaW** [comment]
@curbengh I have changed the default branch to the `master` branch.

**Comment by curbengh** [comment]
https://www.npmjs.com/package/hexo-bunyan/v/2.0.0
CHANGES.md is only applicable to the upstream, thus not published.

Upstream's 2.0.0 tag is renamed to [2.0.0-upstream](https://github.com/hexojs/hexo-bunyan/releases/tag/2.0.0-upstream) to make way for our [2.0.0](https://github.com/hexojs/hexo-bunyan/releases/tag/2.0.0).

**Pull request merged**
